# Generated by Django 4.1.7 on 2023-03-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_favorite_advertisement_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
